# Generated by Django 4.2.2 on 2023-07-05 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(related_name='books_liked', through='books.BooksLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
