# Generated by Django 4.2.2 on 2023-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booksuser',
            name='user_follow',
            field=models.BooleanField(default=True),
        ),
    ]
