# Generated by Django 4.2.2 on 2023-07-12 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_alter_book_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookslikes',
            unique_together={('book', 'user')},
        ),
    ]
