# Generated by Django 4.2.2 on 2023-07-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='loan',
            name='returned_date',
            field=models.DateTimeField(null=True),
        ),
    ]
